markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
#excerpt_separator: "<!-- more -->"    在jekyll官方的语法中，在此处加上此句，然后在index.html文件中加上{{ post.excerpt }}此句即可

github: TeslaHua
author: "王中华"
email: wangzhonghua_cnu@163.com
name: "王中华个人博客"
domain: www.teslahua.com
all_categories: [
["java", "Java后台相关","/posts/java.html"],
["web", "Web前端相关","/posts/web.html"],
["database", "数据库相关","/posts/database.html"],
["embedded", "嵌入式设计相关","/posts/embedded.html"],
["Linux", "Linux相关","/posts/linux.html"],
["hardware", "硬件设计相关","/posts/hardware.html"],
["about", "关于","/posts/about.html"],
["read", "读书笔记","/posts/read.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate
