markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: TeslaHua
author: "王中华"
email: wangzhonghua_cnu@163.com
name: "王中华个人博客"
domain: www.panxw.com
all_categories: [
["java", "Java后台相关","/posts/java.html"],
["web", "Web前端相关","/posts/web.html"],
["database", "数据库相关","/posts/database.html"],
["embedded", "嵌入式设计相关","/posts/embedded.html"],
["Linux", "Linux相关","/posts/linux.html"],
["hardware", "硬件设计相关","/posts/hardware.html"],
["about", "关于","/posts/about.html"],
["read", "读书笔记","/posts/read.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate

# Gitment
gitment:
enable: true
githubID: TeslaHUa
repo: https://github.com/TeslaHua/TeslaHua.github.io.git
ClientID: 0f1b792c389050e22d2e
ClientSecret: a85a92835f8831731511a47e40dcc3855574d176
lazy: false
